In [1]:
import torch
import numpy as np

In [2]:
print("PyTorch version {}".format(torch.__version__))
print("GPU-enabled installation? {}".format(torch.cuda.is_available()))

PyTorch version 1.0.1.post2
GPU-enabled installation? False


# create a Float type of tensor

In [8]:
# create a Float type of tensor with size 2 by 3
t = torch.FloatTensor(2, 3)
print(t, t.size())

tensor([[ 0.0000e+00,  4.6566e-10, -1.6603e+29],
        [ 2.0005e+00,  2.8026e-45,  0.0000e+00]]) torch.Size([2, 3])


In [9]:
# The underscore after the method name is important: it means that the operation happens in place, 
# this is, the returned object is the same object but now with different content.
t.zero_()
print(t)
# as oppose to
t = torch.zeros(2, 3)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# create a Float type of tensor with specific number in specific position
torch.FloatTensor([[1, 2, 3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# convert PyTorch with NumPy

In [10]:
# Create a new multi-dimensional array in NumPy with the np datatype (np.float32)
a = np.array([1., 2., 3.])

# Convert the array to a torch tensor
t = torch.tensor(a)

print("NumPy array: {}, type: {}".format(a, a.dtype))
print("Torch tensor: {}, type: {}".format(t, t.dtype))

NumPy array: [1. 2. 3.], type: float64
Torch tensor: tensor([1., 2., 3.], dtype=torch.float64), type: torch.float64


In [11]:
# convert from Tensor back to Numpy
t.numpy()

array([1., 2., 3.])